### ISSUE TITLE
Make a better method to get item weight

### ISSUE THREAD

**Issue by Insane96** [Insane96/IguanaTweaksReborn#94]
This happens frequently, even with other mods

```
java.lang.IllegalArgumentException: Cannot set property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} to down on block jasbtweaks:cobblestone_generator, it is not an allowed value
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.withProperty(BlockStateContainer.java:233)
	at insane96mcp.jasbtweaks.block.BlockCobblestoneGen.getStateFromMeta(BlockCobblestoneGen.java:226)
	at net.insane96mcp.iguanatweaks.modules.ModuleMovementRestriction.getItemWeight(ModuleMovementRestriction.java:425)
	at net.insane96mcp.iguanatweaks.modules.ModuleMovementRestriction.GetStackWeight(ModuleMovementRestriction.java:140)
	at net.insane96mcp.iguanatweaks.modules.ModuleMovementRestriction.RenderWeightTooltip(ModuleMovementRestriction.java:155)
	at net.insane96mcp.iguanatweaks.events.ItemTooltip.EventItemTooltip(ItemTooltip.java:16)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_18_ItemTooltip_EventItemTooltip_ItemTooltipEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:358)
	at net.minecraft.item.ItemStack.getTooltip(ItemStack.java:993)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:626)
	at net.minecraft.client.util.SearchTree.index(SearchTree.java:93)
	at net.minecraft.client.util.SearchTree.add(SearchTree.java:78)
	at java.lang.Iterable.forEach(Unknown Source)
	at net.minecraft.client.Minecraft.populateSearchTreeManager(Minecraft.java:640)
	at net.minecraft.client.Minecraft.init(Minecraft.java:576)
	at net.minecraft.client.Minecraft.run(Minecraft.java:422)
	at net.minecraft.client.main.Main.main(Main.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.gradle.GradleStartCommon.launch(GradleStartCommon.java:97)
	at GradleStart.main(GradleStart.java:25)
```

**Comment by Insane96** [comment]
Should no longer be a problem in 1.15 since meta is gone
