### ISSUE TITLE
You can be compatible with the Furenikus_Roads mod?

### ISSUE THREAD

**Issue by Abo233** [Insane96/IguanaTweaksReborn#95]
It is not compatible "movement restriction" this setting

This is the error report

Time: 11/8/19 6:55 PM
Description: Initializing game

java.lang.IllegalArgumentException: Cannot set property PropertyDirection{name=zz_facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} to down on block furenikusroads:line_white_side_double, it is not an allowed value
	at pl.asie.foamfix.common.FoamyBlockState.func_177226_a(FoamyBlockState.java:59)
	at com.silvaniastudios.roads.blocks.paint.SideLinePaintBlock.func_176203_a(SideLinePaintBlock.java:56)
	at net.insane96mcp.iguanatweaks.utils.Utils.GetItemWeight(Utils.java:26)
	at net.insane96mcp.iguanatweaks.modules.ModuleMovementRestriction.GetStackWeight(ModuleMovementRestriction.java:138)
	at net.insane96mcp.iguanatweaks.modules.ModuleMovementRestriction.RenderWeightTooltip(ModuleMovementRestriction.java:153)
	at net.insane96mcp.iguanatweaks.events.ItemTooltip.EventItemTooltip(ItemTooltip.java:16)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_409_ItemTooltip_EventItemTooltip_ItemTooltipEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:358)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:889)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:576)
	at net.minecraft.client.Minecraft$$Lambda$2345.000000002C346110.apply(Unknown Source)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at net.minecraft.client.Minecraft$$Lambda$2384.000000002AEABE00.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:590)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:529)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at pl.asie.foamfix.common.FoamyBlockState.func_177226_a(FoamyBlockState.java:59)
	at com.silvaniastudios.roads.blocks.paint.SideLinePaintBlock.func_176203_a(SideLinePaintBlock.java:56)
	at net.insane96mcp.iguanatweaks.utils.Utils.GetItemWeight(Utils.java:26)
	at net.insane96mcp.iguanatweaks.modules.ModuleMovementRestriction.GetStackWeight(ModuleMovementRestriction.java:138)
	at net.insane96mcp.iguanatweaks.modules.ModuleMovementRestriction.RenderWeightTooltip(ModuleMovementRestriction.java:153)
	at net.insane96mcp.iguanatweaks.events.ItemTooltip.EventItemTooltip(ItemTooltip.java:16)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_409_ItemTooltip_EventItemTooltip_ItemTooltipEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:358)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:889)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:576)
	at net.minecraft.client.Minecraft$$Lambda$2345.000000002C346110.apply(Unknown Source)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at net.minecraft.client.Minecraft$$Lambda$2384.000000002AEABE00.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:590)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:529)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

**Comment by Abo233** [comment]
I have already been tested

**Comment by Insane96** [comment]
This is already "in the works" #94
