### ISSUE TITLE
Weight feature not working with Cave Expansion mod

### ISSUE THREAD

**Issue by hasuu** [Insane96/IguanaTweaksReborn#96]
Minecraft Version: 1.12.2
Mod Version:1.5
Forge Version:14.23.5.2847
What Happens:Crashes on start up
Logs / Crash reports:
---- Minecraft Crash Report ----
Description: Initializing game
java.lang.IllegalArgumentException: Cannot set property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} to down on block cave_expansion:treasurelvl3, it is not an allowed value
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177226_a(BlockStateContainer.java:227)
	at net.mcreator.cave_expansion.MCreatorTreasureLVL3$BlockCustom.func_176203_a(MCreatorTreasureLVL3.java:101)
	at net.insane96mcp.iguanatweaks.utils.Utils.GetItemWeight(Utils.java:26)
	at net.insane96mcp.iguanatweaks.modules.ModuleMovementRestriction.GetStackWeight(ModuleMovementRestriction.java:138)
	at net.insane96mcp.iguanatweaks.modules.ModuleMovementRestriction.RenderWeightTooltip(ModuleMovementRestriction.java:153)
	at net.insane96mcp.iguanatweaks.events.ItemTooltip.EventItemTooltip(ItemTooltip.java:16)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_7_ItemTooltip_EventItemTooltip_ItemTooltipEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:358)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:889)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:576)
	at net.minecraft.client.Minecraft$$Lambda$144/457709322.apply(Unknown Source)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at net.minecraft.client.Minecraft$$Lambda$146/897613182.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:590)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:529)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177226_a(BlockStateContainer.java:227)
	at net.mcreator.cave_expansion.MCreatorTreasureLVL3$BlockCustom.func_176203_a(MCreatorTreasureLVL3.java:101)
	at net.insane96mcp.iguanatweaks.utils.Utils.GetItemWeight(Utils.java:26)
	at net.insane96mcp.iguanatweaks.modules.ModuleMovementRestriction.GetStackWeight(ModuleMovementRestriction.java:138)
	at net.insane96mcp.iguanatweaks.modules.ModuleMovementRestriction.RenderWeightTooltip(ModuleMovementRestriction.java:153)
	at net.insane96mcp.iguanatweaks.events.ItemTooltip.EventItemTooltip(ItemTooltip.java:16)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_7_ItemTooltip_EventItemTooltip_ItemTooltipEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.event.ForgeEventFactory.onItemTooltip(ForgeEventFactory.java:358)
	at net.minecraft.item.ItemStack.func_82840_a(ItemStack.java:889)
	at net.minecraft.client.Minecraft.lambda$populateSearchTreeManager$1(Minecraft.java:576)
	at net.minecraft.client.Minecraft$$Lambda$144/457709322.apply(Unknown Source)
	at net.minecraft.client.util.SearchTree.func_194042_b(SourceFile:49)
	at net.minecraft.client.util.SearchTree.func_194043_a(SourceFile:44)
	at net.minecraft.client.Minecraft$$Lambda$146/897613182.accept(Unknown Source)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at net.minecraft.client.Minecraft.func_193986_ar(Minecraft.java:590)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:529)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 361543912 bytes (344 MB) / 805306368 bytes (768 MB) up to 4294967296 bytes (4096 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 6 mods loaded, 6 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID             | Version      | Source                                 | Signature |
	|:----- |:-------------- |:------------ |:-------------------------------------- |:--------- |
	| LCH   | minecraft      | 1.12.2       | minecraft.jar                          | None      |
	| LCH   | mcp            | 9.42         | minecraft.jar                          | None      |
	| LCH   | FML            | 8.0.99.99    | forge-1.12.2-14.23.5.2847.jar          | None      |
	| LCH   | forge          | 14.23.5.2847 | forge-1.12.2-14.23.5.2847.jar          | None      |
	| LCH   | cave_expansion | 1.5.0        | CaveExpansionV1.5.jar                  | None      |
	| LCH   | iguanatweaks   | 1.4.20       | IguanaTweaksReborn-1.4.20-mc1.12.x.jar | None      |

	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 440.97' Renderer: 'GeForce GTX 970/PCIe/SSE2'
	Launched Version: 1.12.2-forge1.12.2-14.23.5.2847
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.6.0 NVIDIA 440.97, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: AudioCraftV1.6.zip, Better Vanilla 1.7.1 [1.12].zip, Consistency-1.6.1.zip, Minecraftic Geolosys-1.3.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 4x Intel(R) Core(TM) i5-4670K CPU @ 3.40GHz

Config: Tried setting all items from cave expansion to weight 0 but didn't help

List of mods installed / modpack: Cave Expansion with Iguana

**Comment by Insane96** [comment]
net.**mcreator**

**Comment by hasuu** [comment]
What do u mean bro?

**Comment by Insane96** [comment]
That the mod is made with MCreator and code sucks with it

**Comment by Insane96** [comment]
Also next time pastebin.com or gist.github.com for logs ty

**Comment by hasuu** [comment]
smart ass

**Comment by Insane96** [comment]
What
